const TRANSITION_SHORT = 200
const TRANSITION_MEDIUM = 500
const TRANSITION_LONG = 10000
const EASING_OUT_QUART = 'cubic-bezier(0.165, 0.84, 0.44, 1);'
const EASING_LINEAR = 'linear'

const TRANSITION_PRIMARY = `${TRANSITION_MEDIUM}ms ${EASING_OUT_QUART}`
const TRANSITION_SECONDARY = `${TRANSITION_LONG}ms ${EASING_LINEAR}`
const DURATION_PRIMARY = TRANSITION_MEDIUM
const DURATION_SECONDARY = TRANSITION_LONG
const DURATION_GAP = TRANSITION_SHORT

export default {
  TRANSITION_PRIMARY,
  TRANSITION_SECONDARY,
  DURATION_PRIMARY,
  DURATION_SECONDARY,
  DURATION_GAP,
  EASING_LINEAR,
}
