const COLOR_WHITE = '#FFFFFF'
const COLOR_GREEN = '#00EFB2'
// const COLOR_DARK = '#010234'
const GRADIANT = 'linear-gradient(90deg, #c127b9 0%, #ff316d 100%)'
const DARK_GREEN = '#164A41'
const MEDIUM_GREEN = '#4D774E'
const LIGHT_GREEN = '#9DC88D'
const NATURAL_YELLOW = '#F1B24A'

const COLOR_IDENTITY = COLOR_GREEN

const COLOR_BUTTON = GRADIANT

const TEXT_PRIMARY = COLOR_WHITE
const TEXT_SECONDARY = NATURAL_YELLOW
const TEXT_OVERLAY = DARK_GREEN
const BACKGROUND_PRIMARY = DARK_GREEN
const BACKGROUND_SECONDARY = LIGHT_GREEN
const BACKGROUND_MEDIUM = MEDIUM_GREEN

export default {
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TEXT_OVERLAY,
  COLOR_IDENTITY,
  COLOR_BUTTON,
  BACKGROUND_PRIMARY,
  BACKGROUND_SECONDARY,
  BACKGROUND_MEDIUM,
}
