const FONT_SIZE_REGULAR = '16px'
const FONT_SIZE_MEDIUM = '20px'
const FONT_SIZE_MEDIUM_LARGE = '28px'
const FONT_SIZE_LARGE = '36px'

const FONT_HEADING = FONT_SIZE_LARGE
const FONT_HEADING_MOBILE = FONT_SIZE_MEDIUM_LARGE

const FONT_SUBHEADING = FONT_SIZE_MEDIUM

export default {
  FONT_SIZE_REGULAR,
  FONT_HEADING,
  FONT_HEADING_MOBILE,
  FONT_SUBHEADING,
}
